kind: Pod
apiVersion: v1
metadata:
  name: sharepath-provisioner
spec:
  containers:
    - name: sharepath-provisioner
      image: poeticloud/sharepath-provisioner:v1.0.0
      imagePullPolicy: "IfNotPresent"
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumeMounts:
        - name: pv-volume
          mountPath: /tmp/sharepath-provisioner
  serviceAccountName: sharepath-provisioner
  volumes:
    - name: pv-volume
      hostPath:
        path: /tmp/sharepath-provisioner
