kind: Pod
apiVersion: v1
metadata:
  name: sharepath-provisioner
spec:
  containers:
    - name: sharepath-provisioner
      image: 192.168.10.171:5000/sharepath-provisioner:v1.0.7
      imagePullPolicy: "IfNotPresent"
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_HOST_PATH
          value: "/sharepath"
      volumeMounts:
        - name: pv-volume
          mountPath: /sharepath
  serviceAccountName: sharepath-provisioner
  volumes:
    - name: pv-volume
      hostPath:
        path: /sharepath
