kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sharepath-pvc
spec:
  storageClassName: "example-sharepath"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
